engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        #mass_threshold: 30
      - javascript
ratings:
  paths:
  - lib/main.min.js
exclude_paths:
  -bower_components
  -node_modules
  -lib/classie.js
  -lib/modernizr.custom.js
  -js/*
  -lib/main.min.js
